import os
import ast
from pathlib import Path

def get_python_files(root_dir, ignored_dirs):
    py_files = []
    for dirpath, dirnames, filenames in os.walk(root_dir):
        # Exclude hidden directories and ignored directories
        dirnames[:] = [d for d in dirnames if d not in ignored_dirs and not d.startswith('.')]
        for f in filenames:
            if f.endswith('.py'):
                py_files.append(os.path.join(dirpath, f))
    return py_files

def parse_imports(filepath):
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            tree = ast.parse(f.read(), filename=filepath)
    except SyntaxError:
        return set()
    except Exception:
        return set()
    
    imports = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                imports.add(alias.name.split('.')[0])
        elif isinstance(node, ast.ImportFrom):
            if node.module:
                imports.add(node.module.split('.')[0])
            elif node.level > 0:
                # relative import like `from . import db`
                for alias in node.names:
                    imports.add(alias.name.split('.')[0])
    return imports

def main():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    root_dir = os.path.abspath(os.path.join(script_dir, '..'))
    
    # Exclude venvs and non-project folders
    ignored_dirs = {
        'venv', 'venv2', '.git', '.gitnexus', 'GitNexus-main', 
        'Visualization of my code', '__pycache__', 'env', '.venv', '.claude'
    }
    
    py_files = get_python_files(root_dir, ignored_dirs)
    
    nodes = {}
    internal_modules = set()
    
    for filepath in py_files:
        rel_path = os.path.relpath(filepath, root_dir)
        module_name = Path(rel_path).stem  # e.g. "config", "downloader"
        internal_modules.add(module_name)
        imports = parse_imports(filepath)
        
        # Keep track with full relative path to prevent collisions, but use stem for matching
        nodes[rel_path] = {
            'stem': module_name,
            'imports': list(imports)
        }
        
    # Build mermaid
    mermaid_lines = ["```mermaid", "graph TD"]
    mermaid_lines.append("    %% Styling")
    mermaid_lines.append("    classDef internal fill:#3b82f6,stroke:#1d4ed8,stroke-width:2px,color:#fff;")
    mermaid_lines.append("    classDef external fill:#10b981,stroke:#047857,stroke-width:2px,color:#fff;")
    
    mermaid_lines.append("    subgraph QDArchive Architecture")
    
    # First, declare all internal nodes so they render beautifully
    for rel_path, data in nodes.items():
        node_id = data['stem'].replace(' ', '_').replace('-', '_')
        node_label = f"\"{data['stem']}\""
        mermaid_lines.append(f"    {node_id}[{node_label}]:::internal")
        
    mermaid_lines.append("    %% Dependencies")
    
    external_deps_added = set()
    
    for rel_path, data in nodes.items():
        node_id = data['stem'].replace(' ', '_').replace('-', '_')
        for imp in data['imports']:
            imp_id = imp.replace(' ', '_').replace('-', '_')
            if imp in internal_modules:
                mermaid_lines.append(f"    {node_id} --> {imp_id}")
            else:
                # Avoid standard library spam by ignoring common ones if possible
                # But to keep it simple, we include them as external dependencies
                # We filter out very common builtin modules to keep graph readable
                builtins = {'os', 'sys', 'json', 'time', 'datetime', 'pathlib', 'typing', 'logging', 're', 'copy', 'csv', 'math'}
                if imp not in builtins and imp:
                    if imp not in external_deps_added:
                        mermaid_lines.append(f"    {imp_id}[[{imp}]]:::external")
                        external_deps_added.add(imp)
                    mermaid_lines.append(f"    {node_id} -.-> {imp_id}")
                
    mermaid_lines.append("    end")
    mermaid_lines.append("```")
    
    # Write to Architecture.md
    out_path = os.path.join(script_dir, 'Architecture.md')
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write("# Project Architecture & Flow\n\n")
        f.write("This knowledge graph visualizes the code structure, modules, and their dependencies within the QDArchive project.\n")
        f.write("Internal modules are shown in blue, and external dependencies in green.\n\n")
        f.write('\n'.join(mermaid_lines))
        f.write("\n\n*Auto-generated by custom architecture script. Re-run `python generate_graph.py` to update after code changes.*")
        
    print(f"Generated Architecture.md with {len(nodes)} modules and {len(external_deps_added)} external dependencies.")

if __name__ == '__main__':
    main()
